language: ruby
rvm:
  - 2.2.10
  - 2.4.10
  - 2.7.6
  - 3.1.2
  - truffleruby
install:
  - bundle install --jobs=3 --retry=3
services:
  - redis-server
cache:
  - bundler
env:
  - REDIS_PORT=6379
script:
  - bundle exec rspec
notifications:
  email:
    on_success: change
    on_failure: change
